#!/bin/sh


word=$(zenity --entry --text "Please enter an English word")
line=$(grep -iwnm 1 $word Swadesh_EN.txt  | sed -n 's/^\([0-9]*\)[:].*/\1/p')
if [ $line ]
then 
	yWord=`sed "${line}q;d" Swadesh_YR.txt`
	zenity --info --text "Yoruba word for \"$word\" is: \"$yWord\""
else
	zenity --info --text "Word not found in dictionary"
fi 




