#!/bin/sh


#read in the argument(s) from console

if [ $# ]
#Check if argument list is not null
then
	WORD=$1 #assign first argument to variable
	line=$(grep -iwnm 1 $WORD Swadesh_EN.txt | sed -n 's/^\([0-9]*\)[:].*/\1/p')
	#if $line is not set, echo word not found
	if [ $line ]
	then 
		yWord=`sed "${line}q;d" Swadesh_YR.txt`
		echo "Yoruba word for \"$WORD\" is: \"$yWord\""
	else
		echo "Word not found in dictionary"
	fi 
else
	echo "Please supply word to be translated"
fi




